name: 'pbi-milestone'

runs:
  using: 'composite'
  steps:
    - name: PBI milestone
      run: |
        ruby -r json -r shellwords -e '
            pr_json = JSON.parse(`curl -H "authorization: Bearer ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}"`)

            description = pr_json["body"]
            matched     = /## PBI Issue\s+- #(?<issue_no>\d+)/.match(description)

            return if matched.nil?

            issue_no = matched[:issue_no]

            issue = JSON.parse(`curl -H "authorization: Bearer ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/#{issue_no}"`)

            if issue["labels"].any?{|label| label["name"] == "PBI" } && !issue["milestone"].empty?
              params = {milestone: issue["milestone"]["number"]}
              `curl -X PATCH -H "authorization: Bearer ${{ github.token }}" \
              -d #{Shellwords.escape(params.to_json)} \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}"`
            end
          '
      shell: bash
