name: pbi-auto-link
on:
  pull_request:
    types: [opened, edited]

jobs:
  pbi-auto-link:
    runs-on: ubuntu-20.04
    steps:
      - name: Get pull request number
        run: |
          pr=$(curl -X GET -H "authorization: Bearer ${{ github.token }}" \
                  https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.base_ref }}&per_page=1)
          echo "::set-output name=pr_number::$(echo "$pr" | jq '.[].number')"
        id: get-pr-number
        shell: bash
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pbi-issue
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CURRENT_PULL_REQUEST_NUMBER: ${{ github.event.number}}
      - name: Set pbi issue
        run: |
          ruby -r json -r shellwords -e '
            event_json  = JSON.parse(File.read(ENV["GITHUB_EVENT_PATH"]))
            issue = JSON.parse(`curl -H "authorization: Bearer ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.get-pr-number.outputs.pr_number }}"`)


            issue_no = /## PBI Issue\s+- #(?<issue_no>\d+)/.match(issue["body"])[:issue_no]

            new_body = event_json["pull_request"]["body"].gsub(/## PBI Issue\s+- /, "## PBI Issue\n\n- ##{issue_no}")

            params = {body: "#{new_body}"}
            res = JSON.parse(`curl -X PATCH -H "authorization: Bearer ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/6" \
            -d #{Shellwords.escape(params.to_json)}`)

            p res
          '
