name: PBI milestone
on:
  pull_request:
    types: [opened, edited]

jobs:
  build:
    name: set milestone
    runs-on: ubuntu-latest
    if: github.event.pull_request.milestone == null
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pbi-milestone
